"""
Writes the new Smart Tiered Pipeline ai.js
"""

lines = []
def L(s=""): lines.append(s)

# ── Заголовок ──────────────────────────────────────────────────────────────
L("const fs   = require('fs');")
L("const pdfParse  = require('pdf-parse');")
L("const mammoth   = require('mammoth');")
L("const textract  = require('textract');")
L("const xlsx      = require('xlsx');")
L()
L("const OLLAMA_URL   = process.env.OLLAMA_URL   || 'http://localhost:11434';")
L("const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'llama3';")
L()
L("const isDev = process.env.NODE_ENV !== 'production';")
L("const log   = (...args) => { if (isDev) console.log(...args); };")
L()

# ── Категорії ──────────────────────────────────────────────────────────────
L("const VALID_CATEGORIES = [")
L("  \"Системи зв'язку\",")
L("  'Кібербезпека',")
L("  'Криптографія',")
L("  'Нормативні акти',")
L("  'Радіоелектронна боротьба',")
L("  'IT-термінологія',")
L("];")
L()

# ── Keyword classifier ─────────────────────────────────────────────────────
L("function classifyTermByKeywords(termName, definition) {")
L("  const text = (termName + ' ' + (definition || '')).toLowerCase();")
L("  const rules = [")
L("    { category: 'Нормативні акти', keywords: [")
L("        'наказ','положення','інструкція','стандарт','регламент','закон ',")
L("        'постанова','директива','нормативний','нормативні','правила',")
L("        'статут','кодекс','доктрина','настанова','керівництво','дсту',")
L("        'stanag','вимоги','норма ','порядок ','затверджено','затвердження',")
L("        'документація','регулювання','перелік ','типовий','відомчий',")
L("        'процедура','технічні умови','технічні вимоги','циркуляр',")
L("        'розпорядження','концепція','протокол наради'] },")
L("    { category: \"Системи зв'язку\", keywords: [")
L("        \"зв'язк\",\"зв'язк\",'зв`язк','радіостанц','антена','ретранслятор',")
L("        'вузол зв','засоби зв','телефон','телеграф','супутников','стільников',")
L("        'транкінг','sincgars','маршрутизатор','радіоканал','канал зв',")
L("        'лінія зв','апаратура','польовий вузол','абонентськ','радіозв',")
L("        'кабельн','волоконно-оптич','ствольн','тропосфер','вузловий',")
L("        'техніка зв','організація зв','облік техніки','ремонт техніки',")
L("        'технічне обслуговування','комутатор','перемикач','voip',")
L("        'ip-телефон','диспетчер','кшм','машина зв','засоби радіо'] },")
L("    { category: 'Кібербезпека', keywords: [")
L("        'кібер','вірус','атака','брандмауер','шкідливе програмне забезпечення',")
L("        'шкідливе пз','вразливість','інцидент','cert','soc','пентест',")
L("        'ddos','хакер','кіберзахист','кіберпростір','несанкціонований доступ',")
L("        'захист інформац','інформаційна безпека','кіберінцидент','фішинг',")
L("        'троян','малвар','експлойт','сканування мереж','моніторинг мереж',")
L("        'ips','ids','siem','антивірус'] },")
L("    { category: 'Криптографія', keywords: [")
L("        'крипто','шифрування','дешифрування','ключ шифр','асиметрич',")
L("        'симетрич','цифровий підпис','електронний підпис','ецп','сертифікат',")
L("        'pki','rsa','aes','криптоаналіз','криптографічн','алгоритм шифр',")
L("        'захищений канал','vpn','ssl','tls','hmac','кодування','шифр ',")
L("        'хеш-функц','хешування','хеш '] },")
L("    { category: 'Радіоелектронна боротьба', keywords: [")
L("        'реб ','радіоелектронна боротьба','придушення','глушіння',")
L("        'перехоплення','радіоелектронн','радар','радіолокац','електромагнітн',")
L("        'завада','радіорозвідк','радіоперехоплення','постановник','прицільн',")
L("        'контрбатарейн','локатор','пасивна розвідка','рез ','активна перешкода',")
L("        'пасивна перешкода','електронна боротьба','бпла','дрон',")
L("        'постановник завад'] },")
L("  ];")
L("  const scores = {};")
L("  for (const r of rules) {")
L("    scores[r.category] = 0;")
L("    for (const kw of r.keywords) if (text.includes(kw)) scores[r.category]++;")
L("  }")
L("  const best = Object.entries(scores).sort((a,b) => b[1]-a[1])[0];")
L("  return (best && best[1] > 0) ? best[0] : 'IT-термінологія';")
L("}")
L()

L("function normalizeAndClassify(rawCategory, termName, definition) {")
L("  if (rawCategory) {")
L("    const norm = rawCategory.replace(/['''ʼ＇]/g, '’').trim();")
L("    if (VALID_CATEGORIES.includes(norm)) return norm;")
L("  }")
L("  return classifyTermByKeywords(termName, definition);")
L("}")
L()

# ── Очищення тексту ─────────────────────────────────────────────────────────
L("function cleanDefinition(def) {")
L("  return def.replace(/[;]\\s*$/, '').replace(/^[\\u00AB\\u00BB\\u201C\\u201E\"']|[\\u00AB\\u00BB\\u201D\"']$/g, '').trim();")
L("}")
L()
L("function cleanText(text) {")
L("  return text")
L("    .replace(/^\\s*\\d{1,4}\\s*$/gm, '')")
L("    .replace(/^\\s*[-_=.]{4,}\\s*$/gm, '')")
L("    .replace(/\\n{3,}/g, '\\n\\n')")
L("    .replace(/[ \\t]{2,}/g, ' ')")
L("    .trim();")
L("}")
L()

# ── Парсери файлів ──────────────────────────────────────────────────────────
L("async function extractTextFromPDF(filePath) {")
L("  const dataBuffer = fs.readFileSync(filePath);")
L("  if (typeof pdfParse !== 'function') throw new Error('pdf-parse not available');")
L("  const data = await pdfParse(dataBuffer);")
L("  return data.text;")
L("}")
L("async function extractTextFromDOCX(filePath) {")
L("  try { const r = await mammoth.extractRawText({ path: filePath }); return r.value; }")
L("  catch (e) { return extractTextFromDOC(filePath); }")
L("}")
L("async function extractTextFromDOC(filePath) {")
L("  return new Promise((resolve, reject) => {")
L("    textract.fromFileWithPath(filePath, { preserveLineBreaks: true }, (e, t) => e ? reject(e) : resolve(t));")
L("  });")
L("}")
L("async function extractTextFromXLSX(filePath) {")
L("  const workbook = xlsx.readFile(filePath);")
L("  let text = '';")
L("  workbook.SheetNames.forEach(s => {")
L("    text += xlsx.utils.sheet_to_csv(workbook.Sheets[s], { FS: ' ' }) + '\\n\\n';")
L("  });")
L("  return text;")
L("}")
L()

# ── PHASE 1: Аналіз структури документа ────────────────────────────────────
L("/**")
L(" * Розбирає текст на рядки та класифікує кожен:")
L(" *   'def'    — рядок з явним визначенням (термін - визначення)")
L(" *   'header' — заголовок розділу")
L(" *   'prose'  — звичайний текст без явного визначення")
L(" * Повертає { defLines, proseBlocks, glossaryRatio }")
L(" */")
L("function detectDocumentStructure(text) {")
L("  const lines = text.split('\\n');")
L("  const defLines   = [];  // рядки з явними визначеннями")
L("  const proseLines = [];  // решта тексту")
L()
L("  // Паттерн для рядка-визначення: щось - щось АБО щось — щось")
L("  const DEF_LINE = /^([^\\n]{3,80}?)\\s*(?:-|\\u2014|\\u2013)\\s+([^\\n]{15,})$/;")
L("  // Паттерн заголовку: коротко, часто великими або з номером")
L("  const HEADER = /^(\\d[\\d.]*\\.?\\s+)?[А-ЯІЇЄA-Z][^\\n]{0,80}$/;")
L()
L("  for (const line of lines) {")
L("    const trimmed = line.trim();")
L("    if (!trimmed || trimmed.length < 3) continue;")
L()
L("    if (DEF_LINE.test(trimmed)) {")
L("      defLines.push(trimmed);")
L("    } else if (trimmed.length < 100 && HEADER.test(trimmed)) {")
L("      // заголовки пропускаємо (не prose і не def)")
L("    } else {")
L("      proseLines.push(trimmed);")
L("    }")
L("  }")
L()
L("  const total = defLines.length + proseLines.length;")
L("  const glossaryRatio = total > 0 ? defLines.length / total : 0;")
L("  log(`[Structure] def=${defLines.length} prose=${proseLines.length} ratio=${glossaryRatio.toFixed(2)}`);")
L()
L("  return {")
L("    defLines,")
L("    proseText: proseLines.join('\\n\\n'),")
L("    glossaryRatio,")
L("  };")
L("}")
L()

# ── PHASE 2: Швидке витягування з рядків-визначень ─────────────────────────
L("/**")
L(" * Швидкий heuristic-екстрактор для явно визначених рядків.")
L(" * Не потребує LLM. Повертає масив термінів з категоріями.")
L(" */")
L("function extractFromDefinitionLines(defLines) {")
L("  const found = new Map();")
L()
L("  for (const line of defLines) {")
L("    let term = null, def = null;")
L()
L("    // Тип A: em/en dash  \"Термін — визначення\"")
L("    const mDash = line.match(/^([^\\u2014\\u2013\\n]{3,80}?)\\s*[\\u2014\\u2013]\\s*(.{15,})$/);")
L("    if (mDash) { term = mDash[1]; def = mDash[2]; }")
L()
L("    // Тип B: одинарний дефіс  \"термін - визначення;\"  (формат ЗСУ)")
L("    if (!term) {")
L("      const mHyp = line.match(/^([Ѐ-ӿA-Za-z][^\\n]{2,79}?)\\s+-\\s+([Ѐ-ӿ\\w].{14,}?)[;.]?$/);")
L("      if (mHyp && (mHyp[1].match(/-/g)||[]).length < 3)")
L("        { term = mHyp[1]; def = mHyp[2]; }")
L("    }")
L()
L("    // Тип C: \"термін це/є/означає визначення\"")
L("    if (!term) {")
L("      const mIs = line.match(/^([Ѐ-ӿA-Za-z][^\\n]{2,60}?)\\s+(?:це|є|означає)\\s+(.{15,})$/i);")
L("      if (mIs) { term = mIs[1]; def = mIs[2]; }")
L("    }")
L()
L("    if (!term || !def) continue;")
L()
L("    term = term.trim().replace(/^\\d+[\\.)\\s]+/, '').trim();")
L("    def  = cleanDefinition(def);")
L()
L("    if (term.length < 3 || term.length > 80 || def.length < 10 || /^\\d+$/.test(term)) continue;")
L()
L("    const key = term.toLowerCase();")
L("    if (!found.has(key)) {")
L("      found.set(key, {")
L("        term,")
L("        definition: def,")
L("        category: classifyTermByKeywords(term, def),")
L("        extended_info: '',")
L("        definition_source_type: 'Document',")
L("      });")
L("    }")
L("  }")
L()
L("  return Array.from(found.values());")
L("}")
L()

# ── PHASE 3: LLM тільки для prose-тексту ───────────────────────────────────
L("/**")
L(" * Надсилає prose-текст до Ollama для пошуку термінів,")
L(" * яких heuristic не знайшов. Спрощений промпт: тільки term+definition.")
L(" * Категорія призначається keyword-класифікатором після відповіді LLM.")
L(" */")
L("async function extractFromProse(proseText, knownKeys = new Set(), isRetry = false) {")
L("  if (!proseText || proseText.trim().length < 100) return [];")
L()
L("  const retry = isRetry ? 'IMPORTANT: Return ONLY a valid JSON array, no other text.\\n\\n' : '';")
L("  const prompt = retry + `You are a Ukrainian military terminology extractor.")
L("Find technical military terms in the text that are NOT in this known list: ${[...knownKeys].slice(0,30).join(', ')}.")
L()
L("RULES:")
L("- Output ONLY a JSON array. No text before or after.")
L("- Ukrainian only. Copy definitions verbatim from text.")
L("- Skip terms already in known list.")
L("- DO NOT invent definitions. If a term has no definition in text, skip it.")
L()
L("Format: [{\"term\": \"...\", \"definition\": \"...\"}]")
L()
L("TEXT:")
L("${proseText.slice(0, 2500)}`)  // ліміт менший — prose зазвичай щільніший")
L()
L("  try {")
L("    const res = await fetch(`${OLLAMA_URL}/api/generate`, {")
L("      method: 'POST', headers: { 'Content-Type': 'application/json' },")
L("      body: JSON.stringify({ model: OLLAMA_MODEL, prompt, format: 'json', stream: false,")
L("        options: { temperature: 0.1, num_predict: 800 } }),")
L("      signal: AbortSignal.timeout(90000),")
L("    });")
L("    if (!res.ok) throw new Error(`Ollama ${res.status}`);")
L("    const data = await res.json();")
L("    const raw  = (data.response || '').replace(/[\\x00-\\x1F\\x7F-\\x9F]/g, ' ');")
L()
L("    let arr = [];")
L("    try {")
L("      const parsed = JSON.parse(raw.trim());")
L("      arr = Array.isArray(parsed) ? parsed")
L("          : (Array.isArray(parsed?.terms) ? parsed.terms : []);")
L("    } catch {")
L("      const fi = raw.indexOf('['), li = raw.lastIndexOf(']');")
L("      if (fi !== -1 && li > fi) {")
L("        try { arr = JSON.parse(raw.slice(fi, li+1)); } catch { arr = []; }")
L("      }")
L("    }")
L()
L("    const result = arr")
L("      .filter(i => i?.term && i?.definition && !knownKeys.has(i.term.toLowerCase().trim()))")
L("      .map(i => ({")
L("        term: i.term.trim(),")
L("        definition: cleanDefinition(i.definition),")
L("        category: normalizeAndClassify(i.category || '', i.term, i.definition),")
L("        extended_info: '',")
L("        definition_source_type: 'Document',")
L("      }));")
L()
L("    if (result.length === 0 && !isRetry) return extractFromProse(proseText, knownKeys, true);")
L("    return result;")
L("  } catch (e) {")
L("    log('[AI prose] error:', e.message);")
L("    return [];")
L("  }")
L("}")
L()

# ── PHASE 4: Async генерація extended_info ──────────────────────────────────
L("/**")
L(" * Генерує розширений опис для ОДНОГО терміну.")
L(" * Короткий промпт — тільки extended_info (без витягування/категорії).")")
L(" * Викликається асинхронно після підтвердження термінів.")
L(" */")
L("async function generateExtendedInfo(termName, definition) {")
L("  const prompt =")
L("    `Ти — військовий аналітик ЗСУ. Термін: \"${termName}\". Визначення: \"${definition}\".` +")
L("    `\\nНапиши коротку (2-4 речення) ЕНЦИКЛОПЕДИЧНУ ДОВІДКУ українською мовою: роль у ЗСУ, застосування, аналог НАТО.` +")
L("    `\\nВідповідь ТІЛЬКИ JSON: {\"extended_info\": \"...markdown тут...\"}`;")
L()
L("  try {")
L("    const res = await fetch(`${OLLAMA_URL}/api/generate`, {")
L("      method: 'POST', headers: { 'Content-Type': 'application/json' },")
L("      body: JSON.stringify({ model: OLLAMA_MODEL, prompt, format: 'json', stream: false,")
L("        options: { temperature: 0.15, num_predict: 400 } }),")
L("      signal: AbortSignal.timeout(60000),")
L("    });")
L("    if (!res.ok) return '';")
L("    const data   = await res.json();")
L("    const parsed = JSON.parse((data.response || '{}').replace(/```json|```/gi, '').trim());")
L("    return parsed.extended_info || parsed.encyclopedic_info || '';")
L("  } catch { return ''; }")
L("}")
L()

# ── PHASE 4: Async збагачення пачки термінів (викликається після save) ─────
L("/**")
L(" * Збагачує extended_info для пачки draft_terms асинхронно.")
L(" * Викликається після збереження в БД — не блокує UI.")
L(" */")
L("async function enrichDraftTermsBatch(pool, sourceId, limit = 20) {")
L("  try {")
L("    const [rows] = await pool.query(")
L("      `SELECT id, term_name, definition FROM draft_terms")
L("       WHERE source_id = ? AND (extended_info IS NULL OR extended_info = '')`)
L("      LIMIT ?`,")
L("      [sourceId, limit]")
L("    );")
L("    log(`[Enrich] Збагачуємо ${rows.length} чернеток для source #${sourceId}`);")
L("    for (const row of rows) {")
L("      const info = await generateExtendedInfo(row.term_name, row.definition);")
L("      if (info) {")
L("        await pool.query('UPDATE draft_terms SET extended_info = ? WHERE id = ?', [info, row.id]);")
L("      }")
L("    }")
L("    log(`[Enrich] Збагачення завершено для source #${sourceId}`);")
L("  } catch (e) {")
L("    log('[Enrich] error:', e.message);")
L("  }")
L("}")
L()

# ── ГОЛОВНА ФУНКЦІЯ ─────────────────────────────────────────────────────────
L("/**")
L(" * Smart Tiered Pipeline:")
L(" *  1. Витягуємо текст з файлу")
L(" *  2. Аналізуємо структуру → def-рядки vs prose")
L(" *  3. Heuristic-екстрактор для def-рядків (миттєво, без LLM)")
L(" *  4. LLM тільки для prose (якщо є і heuristic знайшов мало)")
L(" *  5. Keyword-класифікатор для всіх термінів")
L(" *  Результат — масив термінів готовий до збереження.")
L(" */")
L("async function processDocument(filePath, progressCallback = async () => {}, accessLevel = 'Public') {")
L("  let text = '';")
L("  const ext = filePath.split('.').pop().toLowerCase();")
L()
L("  await progressCallback(5, 'Зчитування тексту документа...');")
L("  try {")
L("    if      (ext === 'pdf')  text = await extractTextFromPDF(filePath);")
L("    else if (ext === 'docx') text = await extractTextFromDOCX(filePath);")
L("    else if (ext === 'doc')  text = await extractTextFromDOC(filePath);")
L("    else if (ext === 'xlsx' || ext === 'xls') text = await extractTextFromXLSX(filePath);")
L("    else if (ext === 'txt')  text = fs.readFileSync(filePath, 'utf8');")
L("    else throw new Error('Unsupported file type: ' + ext);")
L("  } catch (e) {")
L("    throw new Error(`Не вдалося прочитати файл: ${e.message}`);")
L("  }")
L()
L("  if (!text.trim()) throw new Error('Документ порожній або не вдалось розпізнати текст.');")
L("  text = cleanText(text);")
L("  log(`[Pipeline] Текст очищено: ${text.length} символів`);")
L()
L("  // ── Phase 1: Аналіз структури ────────────────────────────────────────")
L("  await progressCallback(10, 'Аналіз структури документа...');")
L("  const { defLines, proseText, glossaryRatio } = detectDocumentStructure(text);")
L()
L("  const uniqueMap = new Map();")
L()
L("  // ── Phase 2: Миттєве витягування з def-рядків ────────────────────────")
L("  await progressCallback(20, `Знайдено ${defLines.length} рядків визначень. Обробка...`);")
L("  const heuristicTerms = extractFromDefinitionLines(defLines);")
L("  log(`[Heuristic] Витягнуто ${heuristicTerms.length} термінів`);")
L()
L("  for (const t of heuristicTerms) uniqueMap.set(t.term.toLowerCase(), t);")
L()
L("  if (heuristicTerms.length > 0) {")
L("    await progressCallback(40,")
L("      `Heuristic: знайдено ${heuristicTerms.length} термінів`,")
L("      heuristicTerms);")
L("  }")
L()
L("  // ── Phase 3: LLM для prose (тільки якщо потрібно) ────────────────────")
L("  const GLOSSARY_THRESHOLD  = 0.4;  // якщо > 40% рядків — явний словник")
L("  const MIN_HEURISTIC_TERMS = 3;    // якщо менше — документ без глосарію")
L()
L("  const needsLLM = proseText.trim().length > 200 &&")
L("    (glossaryRatio < GLOSSARY_THRESHOLD || heuristicTerms.length < MIN_HEURISTIC_TERMS);")
L()
L("  if (needsLLM) {")
L("    log(`[Pipeline] Запуск LLM для prose (ratio=${glossaryRatio.toFixed(2)})`);")
L("    await progressCallback(50, 'Пошук термінів у тексті документа (AI)...');")
L()
L("    // Ділимо prose на чанки по 2500 символів з мінімальним перекриттям")
L("    const CHUNK_SIZE    = 2500;")
L("    const PARALLEL_LLM  = 2;")
L("    const proseChunks   = chunkText(proseText, CHUNK_SIZE, 200)")
L("      .filter(c => c.trim().length > 80);")
L()
L("    log(`[Pipeline] ${proseChunks.length} prose-чанків`);")
L()
L("    let processed = 0;")
L("    for (let i = 0; i < proseChunks.length; i += PARALLEL_LLM) {")
L("      const batch   = proseChunks.slice(i, i + PARALLEL_LLM);")
L("      const known   = new Set(uniqueMap.keys());")
L("      const results = await Promise.all(batch.map(c => extractFromProse(c, known)));")
L()
L("      const newTerms = [];")
L("      for (const terms of results) {")
L("        for (const t of terms) {")
L("          const key = t.term.toLowerCase();")
L("          if (!uniqueMap.has(key)) { uniqueMap.set(key, t); newTerms.push(t); }")
L("          else {")
L("            const ex = uniqueMap.get(key);")
L("            if (t.definition.length > ex.definition.length)")
L("              uniqueMap.set(key, { ...ex, definition: t.definition });")
L("          }")
L("        }")
L("      }")
L()
L("      processed += batch.length;")
L("      const pct = 50 + Math.round((processed / proseChunks.length) * 40);")
L("      await progressCallback(pct,")
L("        `AI: блок ${processed}/${proseChunks.length} — ${uniqueMap.size} термінів`,")
L("        newTerms.length ? newTerms : null);")
L("    }")
L("  } else {")
L("    log(`[Pipeline] LLM пропущено (glossaryRatio=${glossaryRatio.toFixed(2)}, terms=${heuristicTerms.length})`);")
L("    await progressCallback(90, 'Документ — структурований словник. LLM не потрібен.');")
L("  }")
L()
L("  // ── Phase 4: Фінальна перевірка категорій ────────────────────────────")
L("  const result = Array.from(uniqueMap.values()).map(item => {")
L("    const kw = classifyTermByKeywords(item.term, item.definition);")
L("    if (item.category === 'IT-термінологія' && kw !== 'IT-термінологія')")
L("      return { ...item, category: kw };")
L("    return item;")
L("  });")
L()
L("  log(`[Pipeline] Готово: ${result.length} унікальних термінів`);")
L("  await progressCallback(95, `Готово! Знайдено ${result.length} термінів.`);")
L("  return result;")
L("}")
L()

# ── chunkText ───────────────────────────────────────────────────────────────
L("function chunkText(text, maxLength, overlapChars = 200) {")
L("  const paragraphs = text.replace(/\\r\\n/g, '\\n').split(/\\n{2,}/).map(p=>p.trim()).filter(Boolean);")
L("  const chunks = []; let current = '', prevTail = '';")
L("  for (const para of paragraphs) {")
L("    if (para.length > maxLength) {")
L("      const sents = para.split(/(?<=[.!?;])\\s+/);")
L("      for (const s of sents) {")
L("        if ((current+' '+s).trim().length > maxLength) {")
L("          if (current) { chunks.push(current.trim()); prevTail = current.slice(-overlapChars); current = prevTail+'\\n\\n'+s; }")
L("          else { chunks.push(s.trim()); prevTail = s.slice(-overlapChars); current = prevTail; }")
L("        } else current = current ? current+' '+s : s;")
L("      }")
L("      continue;")
L("    }")
L("    const cand = current ? current+'\\n\\n'+para : para;")
L("    if (cand.length > maxLength) { chunks.push(current.trim()); prevTail = current.slice(-overlapChars); current = prevTail+'\\n\\n'+para; }")
L("    else current = cand;")
L("  }")
L("  if (current.trim()) chunks.push(current.trim());")
L("  return chunks;")
L("}")
L()

# ── generateDefinitionForTerm (збережено для /admin) ───────────────────────
L("async function generateDefinitionForTerm(termName) {")
L("  const prompt = `The term is: \"${termName}\". You are a Ukrainian military expert.` +")
L("    `\\nWrite a concise academic definition (1-2 sentences) and technical explanation.` +")
L("    `\\nRespond ONLY with valid JSON in Ukrainian: {\"definition\": \"...\", \"extended_info\": \"...\"}`;")
L("  try {")
L("    const res  = await fetch(`${OLLAMA_URL}/api/generate`, {")
L("      method: 'POST', headers: { 'Content-Type': 'application/json' },")
L("      body: JSON.stringify({ model: OLLAMA_MODEL, prompt, format: 'json', stream: false,")
L("        options: { temperature: 0.5 } }),")
L("    });")
L("    if (!res.ok) throw new Error(`Ollama ${res.status}`);")
L("    const d = await res.json();")
L("    return JSON.parse(d.response.trim());")
L("  } catch (e) {")
L("    throw new Error(`Не вдалося згенерувати: ${e.message}`);")
L("  }")
L("}")
L()
L("module.exports = {")
L("  processDocument,")
L("  generateDefinitionForTerm,")
L("  classifyTermByKeywords,")
L("  generateExtendedInfo,")
L("  enrichDraftTermsBatch,")
L("};")

# ── Запис файлу ─────────────────────────────────────────────────────────────
result = '\n'.join(lines)
with open('E:/Диплом/guid_book/backend/ai.js', 'w', encoding='utf-8') as f:
    f.write(result)
print(f"Written: {len(result)} chars, {result.count(chr(10))} lines")
